services:
  webapp:
    container_name: Container_EnvValue
    image: rmanimaran/containerenvapp:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ENV_SECRET1=Secret1Value
      - ENV_SECRET2=Secret2Value
   
